<?php

namespace RGies\JiraLeadTimeWidgetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WidgetConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WidgetDataRepository extends EntityRepository
{
}
