<?php

namespace RGies\MetricsBundle\Entity;

/**
 * CacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CacheRepository extends \Doctrine\ORM\EntityRepository
{
}
