<?php

namespace Rgies\MetricsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CmsContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CmsContentRepository extends EntityRepository
{
}
