<?php

namespace RGies\MetricsBundle\Entity;

/**
 * CredentialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CredentialRepository extends \Doctrine\ORM\EntityRepository
{
}
