<?php

namespace RGies\MetricsBundle\Entity;

/**
 * DashboardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DashboardRepository extends \Doctrine\ORM\EntityRepository
{
}
