<?php

namespace RGies\MetricsBundle\Entity;

/**
 * JiraCountConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JiraCountConfigRepository extends \Doctrine\ORM\EntityRepository
{
}
