<?php

namespace RGies\MetricsBundle\Entity;

/**
 * RecipeFieldsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeFieldsRepository extends \Doctrine\ORM\EntityRepository
{
}
