<?php

namespace RGies\MetricsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SecurityTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecurityTokenRepository extends EntityRepository
{
}
