<?php

namespace Rgies\MetricsBundle\Entity;

/**
 * WidgetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WidgetsRepository extends \Doctrine\ORM\EntityRepository
{
}
