<?php

namespace RGies\JiraSpendTimeWidgetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WidgetConfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WidgetConfigRepository extends EntityRepository
{
}
